### ISSUE TITLE
构建困难

### ISSUE THREAD

**Issue by pwupink** [AutoAccountingOrg/QianjiPatch#11]
我太菜了不会构建，可不可以发布构建好的release啊，感谢大佬

**Comment by AnkioTomas** [comment]
GithubAction和网盘均有构建版
https://cloud.ankio.net/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E9%92%B1%E8%BF%B9%E8%A1%A5%E4%B8%81/%E6%8C%81%E7%BB%AD%E6%9E%84%E5%BB%BA%E7%89%88
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by pwupink** [comment]
感谢，不过你们的赞赏通道失效了
